-   id: ktlint-wrapper
    name: ktlint wrapper
    entry: ktlint_wrapper
    language: python
    types: [kotlin]
-   id: detekt-wrapper
    name: detekt wrapper
    entry: detekt_wrapper
    language: python
    types: [kotlin]
