-   id: ktlint-wrapper
    name: ktlint wrapper
    entry: python ktlint-wrapper.py
    language: script
    types: [kotlin]
-   id: detekt-wrapper
    name: detekt wrapper
    entry: python detekt-wrapper.py
    language: script
    types: [kotlin]
