-   id: ktlint-wrapper
    name: ktlint wrapper
    entry: ktlint-wrapper
    language: python
    types: [kotlin]
-   id: detekt-wrapper
    name: detekt wrapper
    entry: detekt-wrapper
    language: python
    types: [kotlin]
